name: Github Pages Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install yarn -g
          yarn install
          yarn build:doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          # access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist_docs # The folder the action should deploy.